import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./ChatPipeline.css";

type Lead={chatid:string;nome:string;fone:string;status:string;responsavel:string|null;quando:string;ha:string;ultima:string};
const stages=[{label:"Esperando",value:"",color:"#7c3aed"},{label:"Sem resposta",value:"_sem_resposta",color:"#8490a3"},{label:"Interessado",value:"INTERESSADO",color:"#8b5cf6"},{label:"Teste grátis",value:"TESTE GRÁTIS",color:"#06b6d4"},{label:"Convertido",value:"CONVERTIDO",color:"#10b981"},{label:"Perdido",value:"PERDIDO",color:"#ef4444"},{label:"Removidos",value:"_ocultos",color:"#8490a3"}];
export default function ChatPipeline(){
 const [columns,setColumns]=useState<Lead[][]>(stages.map(()=>[])),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [search,setSearch]=useState(""),[owner,setOwner]=useState(""),[selected,setSelected]=useState<{lead:Lead;removed:boolean}|null>(null),[saving,setSaving]=useState(false);
 const [limits,setLimits]=useState(stages.map(()=>60));
 async function load(){try{const result=await Promise.all(stages.map(async s=>{const r=await fetch(`/api/fila?status=${encodeURIComponent(s.value)}`);if(!r.ok)throw new Error(r.status===401?"Entre no Atendimento para acessar o pipeline de conversas.":"Não foi possível carregar as conversas.");return await r.json() as Lead[]}));setColumns(result);setError("")}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar o pipeline.")}finally{setLoading(false)}}
 useEffect(()=>{void load();const timer=window.setInterval(()=>{void load()},30000);return()=>clearInterval(timer)},[]);
 async function update(path:string,data:Record<string,unknown>){if(!selected)return;setSaving(true);try{const r=await fetch(`/api/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chatid:selected.lead.chatid,...data})});if(!r.ok){const d=await r.json();throw new Error(d.erro||"Não foi possível salvar.")}setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar")}finally{setSaving(false)}}
 const term=search.trim().toLocaleLowerCase("pt-BR");
 const visible=columns.map(list=>list.filter(l=>(!owner||(owner==="_sem"?!l.responsavel:l.responsavel===owner))&&(!term||`${l.nome} ${l.fone}`.toLocaleLowerCase("pt-BR").includes(term)||(/^[\d\s()+.-]+$/.test(term)&&l.fone.replace(/\D/g,"").includes(term.replace(/\D/g,""))))));
 return <div className="chat-pipeline">
  <header className="chat-pipeline-header"><div className="pipeline-switch"><span>Atendimento · principal</span><Link to="/pipeline/anterior">Pipeline anterior</Link></div></header>
  <div className="chat-pipeline-filters"><label>Buscar lead<input placeholder="Nome ou telefone" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Responsável<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Todos</option><option>Lucas</option><option>Dione</option><option value="_sem">Sem responsável</option></select></label><button onClick={()=>{void load()}}>Atualizar</button></div>
  {error&&<div role="alert" className="chat-pipeline-error">{error} <Link to="/atendimento">Abrir Atendimento</Link></div>}
  {loading?<p role="status">Carregando conversas…</p>:<div className="chat-pipeline-board">{stages.map((s,i)=><section className="chat-pipeline-column" key={s.label}><h2><i style={{background:s.color}}/>{s.label}<span>{visible[i].length}</span></h2><div className="chat-pipeline-cards">{visible[i].slice(0,limits[i]).map(l=><button className="chat-pipeline-card" key={l.chatid} onClick={()=>setSelected({lead:l,removed:s.value==="_ocultos"})}><strong>{l.nome||l.fone}</strong><small>{l.fone}</small><span className="chat-pipeline-owner">♙ {l.responsavel||"Sem responsável"}</span><p>{l.ultima||"Sem mensagem disponível"}</p><footer><span>{l.status}</span><time>{l.quando}</time></footer></button>)}{!visible[i].length&&<p className="chat-pipeline-empty">Nenhuma conversa</p>}{visible[i].length>limits[i]&&<button onClick={()=>setLimits(v=>v.map((n,j)=>i===j?n+60:n))}>Mostrar mais</button>}</div></section>)}</div>}
  {selected&&<div className="chat-pipeline-overlay" onClick={()=>!saving&&setSelected(null)}><section role="dialog" aria-modal="true" aria-label="Detalhes do lead" className="chat-pipeline-detail" onClick={e=>e.stopPropagation()}><button autoFocus className="chat-pipeline-close" aria-label="Fechar detalhes" disabled={saving} onClick={()=>setSelected(null)}>×</button><h2>{selected.lead.nome||selected.lead.fone}</h2><p>{selected.lead.fone}</p><p className="chat-pipeline-message">{selected.lead.ultima}</p><label>Etapa comercial<select disabled={saving} value={selected.lead.status} onChange={e=>{void update("status",{status:e.target.value})}}>{!stages.slice(2,6).some(s=>s.value===selected.lead.status)&&<option value={selected.lead.status}>{selected.lead.status||"Selecione"}</option>}{stages.slice(2,6).map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><label>Responsável<select disabled={saving} value={selected.lead.responsavel||""} onChange={e=>{void update("responsavel",{responsavel:e.target.value})}}><option value="">Sem responsável</option><option>Lucas</option><option>Dione</option></select></label><button disabled={saving} onClick={()=>{void update("ocultar",{oculto:!selected.removed})}}>{selected.removed?"Restaurar conversa":"Remover da fila"}</button><p className="chat-pipeline-note">As alterações são compartilhadas com o Atendimento.</p></section></div>}
 </div>
}
