import { useEffect, useState } from "react";
import { DndContext, DragOverlay, MouseSensor, TouchSensor, useSensor, useSensors, useDraggable, useDroppable } from "@dnd-kit/core";
import type { DragEndEvent } from "@dnd-kit/core";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from "recharts";
import { saoPauloDay, shiftDay } from "../lib/period";
import { Link } from "react-router-dom";
import "./ChatPipeline.css";

type OwnerCount={nome:string;responsavel:string;total:number;sem_resposta:number;etapas:Record<string,number>};
type Lead={chatid:string;nome:string;fone:string;status:string;responsavel:string|null;quando:string;ultimo_ts:number|null;ha:string;ultima:string};
const stages=[{label:"Esperando",value:"",color:"#7c3aed"},{label:"Sem resposta",value:"_sem_resposta",color:"#8490a3"},{label:"Interessado",value:"INTERESSADO",color:"#8b5cf6"},{label:"Teste grátis",value:"TESTE GRÁTIS",color:"#06b6d4"},{label:"Convertido",value:"CONVERTIDO",color:"#10b981"},{label:"Perdido",value:"PERDIDO",color:"#ef4444"},{label:"Removidos",value:"_ocultos",color:"#8490a3"}];
function DragCard({lead,stage,disabled,onOpen,children}:{lead:Lead;stage:string;disabled:boolean;onOpen:()=>void;children:React.ReactNode}){
 const {attributes,listeners,setNodeRef,transform,isDragging}=useDraggable({id:stage+":"+lead.chatid,data:{lead,stage},disabled});
 return <button ref={setNodeRef} {...attributes} {...listeners} className="chat-pipeline-card" style={{opacity:isDragging?.3:1,transform:transform?`translate3d(${transform.x}px,${transform.y}px,0)`:undefined}} onClick={()=>{if(!isDragging)onOpen()}}>{children}</button>
}
function DropColumn({stage,disabled,children}:{stage:string;disabled:boolean;children:React.ReactNode}){
 const automatic=stage===""||stage==="_sem_resposta";
 const {setNodeRef,isOver}=useDroppable({id:stage||"waiting",disabled:disabled||automatic});
 return <section ref={setNodeRef} className={"chat-pipeline-column"+(isOver?" chat-pipeline-drop":"")} title={automatic?"Etapa automática conforme a última mensagem":undefined}>{children}</section>
}
export default function ChatPipeline(){
 const [from,setFrom]=useState(""),[to,setTo]=useState("");
 const [ownerCounts,setOwnerCounts]=useState<OwnerCount[]>([]);
 const [columns,setColumns]=useState<Lead[][]>(stages.map(()=>[])),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [search,setSearch]=useState(""),[owner,setOwner]=useState(""),[selected,setSelected]=useState<{lead:Lead;removed:boolean}|null>(null),[saving,setSaving]=useState(false);
 const [dragged,setDragged]=useState<Lead|null>(null);
 const sensors=useSensors(useSensor(MouseSensor,{activationConstraint:{distance:6}}),useSensor(TouchSensor,{activationConstraint:{delay:350,tolerance:8}}));
 const [limits,setLimits]=useState(stages.map(()=>60));
 async function load(){try{const result=await Promise.all(stages.map(async s=>{const r=await fetch(`/api/fila?status=${encodeURIComponent(s.value)}`);if(!r.ok)throw new Error(r.status===401?"Entre no Atendimento para acessar o pipeline de conversas.":"Não foi possível carregar as conversas.");return await r.json() as Lead[]}));setColumns(result);const counts=await fetch("/api/contagem");if(!counts.ok)throw new Error("Não foi possível carregar a distribuição por responsável.");setOwnerCounts((await counts.json())._responsaveis||[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Erro ao carregar o pipeline.")}finally{setLoading(false)}}
 useEffect(()=>{void load();const timer=window.setInterval(()=>{void load()},30000);return()=>clearInterval(timer)},[]);
 async function update(path:string,data:Record<string,unknown>){if(!selected)return;setSaving(true);try{const r=await fetch(`/api/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chatid:selected.lead.chatid,...data})});if(!r.ok){const d=await r.json();throw new Error(d.erro||"Não foi possível salvar.")}setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao salvar")}finally{setSaving(false)}}
 async function move(event:DragEndEvent){
  setDragged(null);if(saving||!event.over)return;
  const target=String(event.over.id),source=event.active.data.current as {lead:Lead;stage:string}|undefined;
  if(!source||!stages.slice(2).some(s=>s.value===target)||target===source.stage)return;
  setSaving(true);setError("");
  async function post(path:string,data:Record<string,unknown>){const r=await fetch(`/api/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chatid:source!.lead.chatid,...data})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.erro||"Não foi possível mover o lead.")}}
  try{if(target==="_ocultos")await post("ocultar",{oculto:true});else{await post("status",{status:target});if(source.stage==="_ocultos")await post("ocultar",{oculto:false})}await load()}catch(e){await load();setError(e instanceof Error?e.message:"Falha ao mover o lead.")}finally{setSaving(false)}
 }
 const term=search.trim().toLocaleLowerCase("pt-BR");
 const visible=columns.map(list=>list.filter(l=>{const day=l.ultimo_ts?new Date(l.ultimo_ts>1e11?l.ultimo_ts:l.ultimo_ts*1000).toLocaleDateString("en-CA",{timeZone:"America/Sao_Paulo"}):"";return (!from||(!!day&&day>=from))&&(!to||(!!day&&day<=to))&&(!owner||(owner==="_sem"?!l.responsavel:l.responsavel===owner))&&(!term||`${l.nome} ${l.fone}`.toLocaleLowerCase("pt-BR").includes(term)||(/^[\d\s()+.-]+$/.test(term)&&l.fone.replace(/\D/g,"").includes(term.replace(/\D/g,""))))}));
 const filteredOwners=from||to||search||owner;
 const uniqueVisible=[...new Map(visible.slice(0,6).flat().map(l=>[l.chatid,l])).values()];
 const displayedOwners=filteredOwners?ownerCounts.filter(r=>!owner||(owner==="_sem"?!r.responsavel:r.responsavel===owner)).map(r=>{const mine=uniqueVisible.filter(l=>(l.responsavel||"")===r.responsavel);const etapas:Record<string,number>=Object.fromEntries(Object.keys(r.etapas).map(k=>[k,0]));mine.forEach(l=>{etapas[l.status]=(etapas[l.status]||0)+1});return {...r,total:mine.length,etapas,sem_resposta:visible[1].filter(l=>(l.responsavel||"")===r.responsavel).length}}):ownerCounts;
 return <div className="chat-pipeline">

  <div className="chat-pipeline-filters"><label>Buscar lead<input placeholder="Nome ou telefone" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Responsável<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">Todos</option><option>Lucas</option><option>Dione</option><option value="_sem">Sem responsável</option></select></label><div className="pipeline-date-presets" aria-label="Atalhos de período">{[{label:"Hoje",days:1},{label:"7d",days:7},{label:"15d",days:15},{label:"30d",days:30},{label:"Mês",days:0}].map(p=>{const today=saoPauloDay(),start=p.days?shiftDay(today,1-p.days):today.slice(0,7)+"-01";return <button key={p.label} aria-pressed={from===start&&to===today} onClick={()=>{setFrom(start);setTo(today)}}>{p.label}</button>})}</div><label>Última mensagem · de<input aria-label="Última mensagem desde" type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></label><label>Até<input aria-label="Última mensagem até" type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></label>{(from||to)&&<button onClick={()=>{setFrom("");setTo("")}}>Limpar período</button>}<button onClick={()=>{void load()}}>Atualizar</button><div className="pipeline-switch"><span>Atendimento · principal</span><Link to="/pipeline/anterior">Pipeline anterior</Link></div></div>
  {error&&<div role="alert" className="chat-pipeline-error">{error} <Link to="/atendimento">Abrir Atendimento</Link></div>}
  {loading?<p role="status">Carregando conversas…</p>:<DndContext sensors={sensors} onDragStart={e=>setDragged(e.active.data.current?.lead||null)} onDragCancel={()=>setDragged(null)} onDragEnd={e=>{void move(e)}}><div className="chat-pipeline-board">{stages.map((s,i)=><DropColumn stage={s.value} disabled={saving} key={s.label}><h2><i style={{background:s.color}}/>{s.label}<span>{visible[i].length}</span></h2><div className="chat-pipeline-cards">{visible[i].slice(0,limits[i]).map(l=><DragCard lead={l} stage={s.value} disabled={saving} key={l.chatid} onOpen={()=>setSelected({lead:l,removed:s.value==="_ocultos"})}><strong>{l.nome||l.fone}</strong><small>{l.fone}</small><span className="chat-pipeline-owner">♙ {l.responsavel||"Sem responsável"}</span><p>{l.ultima||"Sem mensagem disponível"}</p><footer><span>{l.status}</span><time>{l.quando}</time></footer></DragCard>)}{!visible[i].length&&<p className="chat-pipeline-empty">Nenhuma conversa</p>}{visible[i].length>limits[i]&&<button onClick={()=>setLimits(v=>v.map((n,j)=>i===j?n+60:n))}>Mostrar mais</button>}</div></DropColumn>)}</div><DragOverlay>{dragged&&<div className="chat-pipeline-card chat-pipeline-drag-preview"><strong>{dragged.nome||dragged.fone}</strong><small>{dragged.responsavel||"Sem responsável"}</small></div>}</DragOverlay></DndContext>}
  {!loading&&!error&&<section className="pipeline-owner-summary"><h2>Leads por responsável <span>{displayedOwners.reduce((n,r)=>n+r.total,0).toLocaleString("pt-BR")} leads</span></h2><div className="pipeline-owner-grid">{displayedOwners.map(r=><article key={r.nome}><header><strong>{r.nome}</strong><b>{r.total.toLocaleString("pt-BR")}</b></header><div className="pipeline-owner-pie" role="img" aria-label={`Distribuição das etapas de ${r.nome}: ${Object.entries(r.etapas).map(([k,n])=>`${k}: ${n}`).join(", ")}`}>
{r.total>0?<ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={Object.entries(r.etapas).filter(([,n])=>n>0).map(([stage,value])=>({name:stages.find(s=>s.value===stage)?.label||stage,value,stage}))} dataKey="value" nameKey="name" innerRadius={48} outerRadius={72} paddingAngle={2}>{Object.entries(r.etapas).filter(([,n])=>n>0).map(([stage])=><Cell key={stage} fill={stages.find(s=>s.value===stage)?.color||"#8490a3"}/>)}</Pie><Tooltip contentStyle={{background:"var(--color-raised)",border:"1px solid var(--color-edge)",borderRadius:8,color:"var(--color-text)"}}/></PieChart></ResponsiveContainer>:<span className="pipeline-pie-empty">Sem leads no período</span>}<div className="pipeline-pie-total"><b>{r.total}</b><small>leads</small></div></div><div className="pipeline-owner-stages">{[...Object.entries(r.etapas),["_sem_resposta",r.sem_resposta] as [string,number]].map(([stage,n])=>{const info=stages.find(s=>s.value===stage);return <div className="pipeline-owner-stage" key={stage} title={stage==="_sem_resposta"?"Já incluídos no total e nas etapas comerciais":undefined}><div><span>{info?.label||stage}</span><b>{n.toLocaleString("pt-BR")}</b></div><div className="pipeline-stage-track" role="img" aria-label={`${r.nome}, ${info?.label||stage}: ${n} de ${r.total} leads`}><div style={{width:`${Math.min(100,n/Math.max(1,r.total)*100)}%`,background:info?.color||"var(--color-violet)"}}/></div></div>})}</div></article>)}</div></section>}
  {selected&&<div className="chat-pipeline-overlay" onClick={()=>!saving&&setSelected(null)}><section role="dialog" aria-modal="true" aria-label="Detalhes do lead" className="chat-pipeline-detail" onClick={e=>e.stopPropagation()}><button autoFocus className="chat-pipeline-close" aria-label="Fechar detalhes" disabled={saving} onClick={()=>setSelected(null)}>×</button><h2>{selected.lead.nome||selected.lead.fone}</h2><p>{selected.lead.fone}</p><p className="chat-pipeline-message">{selected.lead.ultima}</p><label>Etapa comercial<select disabled={saving} value={selected.lead.status} onChange={e=>{void update("status",{status:e.target.value})}}>{!stages.slice(2,6).some(s=>s.value===selected.lead.status)&&<option value={selected.lead.status}>{selected.lead.status||"Selecione"}</option>}{stages.slice(2,6).map(s=><option key={s.value} value={s.value}>{s.label}</option>)}</select></label><label>Responsável<select disabled={saving} value={selected.lead.responsavel||""} onChange={e=>{void update("responsavel",{responsavel:e.target.value})}}><option value="">Sem responsável</option><option>Lucas</option><option>Dione</option></select></label><button disabled={saving} onClick={()=>{void update("ocultar",{oculto:!selected.removed})}}>{selected.removed?"Restaurar conversa":"Remover da fila"}</button><p className="chat-pipeline-note">As alterações são compartilhadas com o Atendimento.</p></section></div>}
 </div>
}
