import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";
import PeriodFilter from "../components/PeriodFilter";
import { saoPauloDay, shiftDay, inPeriod } from "../lib/period";
import "./TestesGratis.css";
type Entry = { id: string; created_at: string; utm_source: string | null; utm_medium: string | null; utm_campaign: string | null; utm_content: string | null; utm_term: string | null };
const clean = (value: string | null) => { if (!value || value.includes("{{")) return "Não identificado"; try { return decodeURIComponent(value.replace(/\+/g," ")).trim() || "Não identificado"; } catch { return value.trim(); } };
const creative = (r: Entry) => { const c = clean(r.utm_content); return c !== "Não identificado" ? c : /criativo|video/i.test(r.utm_term || "") ? clean(r.utm_term) : c; };
const paid = (r: Entry) => /^(paid_social|cpc|ppc|paid|display|cpm)$/i.test(r.utm_medium || "");
const source = (r: Entry) => { const s = clean(r.utm_source).toLowerCase(); return ["ig","instagram"].includes(s) ? "Instagram" : s === "meta" ? "Meta" : s === "google" ? "Google" : clean(r.utm_source); };
export default function TrafegoPago() {
  const [from,setFrom]=useState(()=>shiftDay(saoPauloDay(),-29)),[to,setTo]=useState(saoPauloDay);
  const [channel,setChannel]=useState("Todos"),[campaign,setCampaign]=useState("Todas"),[sort,setSort]=useState("volume");
  const [rows,setRows]=useState<Entry[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState("");
  useEffect(()=>{let active=true; async function load(){setBusy(true);setError("");try{const count=Math.round((Date.parse(to)-Date.parse(from))/86400000)+1;const previous=shiftDay(from,-count);let all:Entry[]=[];for(let offset=0;;offset+=1000){const r=await supabase.from("landing_leads").select("id,created_at,utm_source,utm_medium,utm_campaign,utm_content,utm_term").gte("created_at",previous+"T00:00:00-03:00").lt("created_at",shiftDay(to,1)+"T00:00:00-03:00").order("id").range(offset,offset+999);if(r.error)throw r.error;all.push(...r.data);if(r.data.length<1000)break;}if(active)setRows(all.filter(paid));}catch{if(active)setError("Não foi possível carregar o tráfego. Recarregue a página para tentar novamente.");}finally{if(active)setBusy(false);}}void load();return()=>{active=false}},[from,to]);
  const data=useMemo(()=>{const days=Math.round((Date.parse(to)-Date.parse(from))/86400000)+1,previousFrom=shiftDay(from,-days),previousTo=shiftDay(from,-1);
    const selected=rows.filter(r=>(channel==="Todos"||source(r)===channel)&&(campaign==="Todas"||clean(r.utm_campaign)===campaign));
    const current=selected.filter(r=>inPeriod(r.created_at,from,to)),previous=selected.filter(r=>inPeriod(r.created_at,previousFrom,previousTo));
    const groups=new Map<string,{name:string;channel:string;campaign:string;count:number;previous:number}>();
    for(const [list,key] of [[current,"count"],[previous,"previous"]] as const){list.forEach(r=>{const name=creative(r),ch=source(r),camp=clean(r.utm_campaign),id=JSON.stringify([name,ch,camp]);const g=groups.get(id)||{name,channel:ch,campaign:camp,count:0,previous:0};g[key]++;groups.set(id,g);});}
    const creatives=[...groups.values()].sort((a,b)=>sort==="trend"?(b.count-b.previous)-(a.count-a.previous):b.count-a.count);
    const channelMap=new Map<string,number>();current.forEach(r=>channelMap.set(source(r),(channelMap.get(source(r))||0)+1));
    return {current,previous,creatives,channels:[...channelMap].sort((a,b)=>b[1]-a[1]),identified:current.filter(r=>creative(r)!=="Não identificado").length};
  },[rows,channel,campaign,from,to,sort]);
  const channels=[...new Set(rows.map(source))].sort(), campaigns=[...new Set(rows.filter(r=>channel==="Todos"||source(r)===channel).map(r=>clean(r.utm_campaign)))].sort();
  const change=(now:number,before:number)=>before?`${now>=before?"+":""}${Math.round((now-before)/before*100)}%` : now ? "Sem base anterior" : "Sem movimento";
  return <div className="trial-dashboard min-h-full p-4 sm:p-6 lg:p-8">
    <header className="rounded-2xl border border-violet/20 bg-gradient-to-br from-violet/10 to-raised p-6"><p className="text-sm font-semibold text-violet-light">◉ MÍDIA E CAMPANHAS</p><h1 className="mt-2 text-3xl font-bold text-bright">Tráfego pago</h1><p className="mt-2 text-base text-muted">Canais, campanhas e criativos por volume de captação.</p></header>
    <PeriodFilter from={from} to={to} onChange={(a,b)=>{setFrom(a);setTo(b);setChannel("Todos");setCampaign("Todas")}}/>
    <div className="mb-5 flex flex-wrap gap-4">{[{label:"Canal",value:channel,options:["Todos",...channels],change:(v:string)=>{setChannel(v);setCampaign("Todas")}}, {label:"Campanha",value:campaign,options:["Todas",...campaigns],change:setCampaign}, {label:"Ordenação",value:sort,options:["volume","trend"],change:setSort}].map(f=><label key={f.label} className="grid min-w-0 max-w-full gap-1 text-sm text-sub">{f.label}<select aria-label={f.label} value={f.value} onChange={e=>f.change(e.target.value)} className="min-h-11 max-w-full rounded-lg border border-edge bg-surface px-3 text-text">{f.options.map(o=><option key={o} value={o}>{o==="volume"?"Mais captações":o==="trend"?"Maior crescimento em volume":o}</option>)}</select></label>)}</div>
    {error&&<p role="alert" className="my-4 text-rose">{error}</p>}
    <div className="grid gap-4 sm:grid-cols-3">{[{label:"Captações pagas registradas",value:data.current.length,detail:"Registros de landing pages no período"},{label:"Criativo identificado",value:`${data.current.length?Math.round(data.identified/data.current.length*100):0}%`,detail:`${data.identified} de ${data.current.length} registros`},{label:"Comparação com período anterior",value:change(data.current.length,data.previous.length),detail:`${data.previous.length} registros no intervalo anterior de igual duração`}].map(c=><article key={c.label} className="rounded-2xl border border-edge bg-raised p-5"><p className="text-sm text-muted">{c.label}</p><strong className="mt-3 block text-3xl text-violet-light">{busy||error?"—":c.value}</strong><p className="mt-2 text-sm text-muted">{c.detail}</p></article>)}</div>
    <section className="mt-5 rounded-2xl border border-edge bg-raised p-5"><h2 className="text-xl font-semibold text-bright">Canais que mais trazem leads</h2><p className="mt-1 text-sm text-muted">Captações com mídia paga identificada no período</p><div className="mt-5 space-y-4">{data.channels.map(([name,count])=><div key={name}><div className="mb-2 flex justify-between text-base text-sub"><span>{name}</span><strong>{count}</strong></div><div className="h-3 rounded-full bg-panel"><div className="h-full rounded-full bg-violet" style={{width:`${data.current.length?count/data.current.length*100:0}%`}}/></div></div>)}</div></section>
    <section className="mt-5"><h2 className="text-xl font-semibold text-bright">Criativos que mais geram leads</h2><p className="mt-1 text-sm text-muted">Cada combinação de criativo, canal e campanha é analisada separadamente.</p><div className="mt-4 grid gap-4 lg:grid-cols-2">{data.creatives.map((c,i)=><article key={JSON.stringify([c.name,c.channel,c.campaign])} className="rounded-2xl border border-edge bg-raised p-5"><div className="flex items-start gap-3"><span className="rounded-lg bg-violet/10 px-3 py-2 font-bold text-violet-light">{i+1}</span><div className="min-w-0"><h3 className="break-words text-lg font-semibold text-bright">{c.name}</h3><p className="mt-1 break-words text-sm text-muted">{c.channel} · {c.campaign}</p></div></div><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><p className="text-3xl font-bold text-cyan">{c.count}<span className="ml-2 text-sm font-normal text-muted">captações</span></p><span className="text-sm text-sub">{data.current.length?(c.count/data.current.length*100).toFixed(1):0}% do período</span></div><div className="mt-3 h-2 rounded-full bg-panel"><div className="h-full rounded-full bg-cyan" style={{width:`${data.current.length?c.count/data.current.length*100:0}%`}}/></div><p className="mt-3 text-sm text-muted">{change(c.count,c.previous)} · anterior: {c.previous} · variação: {c.count-c.previous>0?"+":""}{c.count-c.previous}</p></article>)}</div>{!busy&&!error&&!data.creatives.length&&<p className="rounded-xl border border-edge p-8 text-center text-muted">Nenhum registro de mídia paga neste filtro.</p>}</section>
    <p className="mt-6 text-sm leading-relaxed text-muted">Fonte: registros das landing pages com mídia marcada como paid_social, cpc, ppc, paid, display ou cpm. Os totais são eventos de captação, não pessoas únicas: essa fonte não possui identificador do lead para deduplicar ou vincular testes e vendas. Investimento, impressões, cliques e retorno financeiro não estão disponíveis nesta integração. “Não identificado” inclui marcações ausentes ou não preenchidas.</p>
  </div>;
}
