import { useEffect, useMemo, useState } from "react";
import { Bar, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { saoPauloDay, shiftDay } from "../lib/period";
import "./TrafegoPago.css";

type AdRow = { dia:string; account_id:string; campaign_name:string; adset_name:string; ad_id:string; ad_name:string; spend:number|string; impressions:number; clicks:number; link_clicks:number; landing_page_views:number; leads:number };
type Metric = { spend:number; impressions:number; clicks:number; linkClicks:number; pageViews:number; leads:number };
type Group = Metric & { id:string; name:string; campaign:string; adset:string; previousSpend:number; previousLeads:number };
type IconName = "chart"|"calendar"|"money"|"click"|"leads"|"target"|"filter"|"bulb"|"meta";

const emptyMetric=():Metric=>({spend:0,impressions:0,clicks:0,linkClicks:0,pageViews:0,leads:0});
const add=(m:Metric,r:AdRow)=>{m.spend+=Number(r.spend)||0;m.impressions+=Number(r.impressions)||0;m.clicks+=Number(r.clicks)||0;m.linkClicks+=Number(r.link_clicks)||0;m.pageViews+=Number(r.landing_page_views)||0;m.leads+=Number(r.leads)||0};
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const number=(v:number)=>v.toLocaleString("pt-BR");
const pct=(now:number,before:number)=>before?Math.round((now-before)/before*100):null;
const compactMoney=(v:number)=>v>=1000?`R$ ${(v/1000).toFixed(1).replace(".",",")} mil`:money(v);
const colors=["#8b5cf6","#06b6d4","#10b981","#f59e0b","#f43f5e"];

function Icon({name,className="h-5 w-5"}:{name:IconName;className?:string}){
  const path:Record<IconName,React.ReactNode>={
    chart:<><path d="M4 20V10m6 10V4m6 16v-7m6 7H2"/><path d="m3 7 6-4 6 5 7-5"/></>,
    calendar:<><rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 10h18"/></>,
    money:<><circle cx="12" cy="12" r="9"/><path d="M15.5 8.5c-1-1.2-6-1.1-6 1.2 0 2.7 6 1 6 4 0 2.4-5.1 2.5-7 1M12 6v12"/></>,
    click:<><path d="m5 3 13 9-6 1-3 6L5 3Z"/><path d="m13 14 4 5"/></>,
    leads:<><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/></>,
    target:<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/></>,
    filter:<><path d="M4 5h16l-6 7v5l-4 2v-7L4 5Z"/></>,
    bulb:<><path d="M9 18h6M10 22h4"/><path d="M8.5 14.5A7 7 0 1 1 15.5 14.5C14.5 15.4 14 16 14 18h-4c0-2-.5-2.6-1.5-3.5Z"/></>,
    meta:<><path d="M2.5 16.5c2.7-8.8 5-12 7.2-12 2.7 0 4.2 7.4 6.1 11.2 1 2 2 3.3 3.4 3.3 1.6 0 2.3-1.8 2.3-4.2 0-5.8-3-10.3-6.7-10.3-4.4 0-7.6 6.8-12.3 12Z"/></>,
  };return <svg aria-hidden="true" className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round">{path[name]}</svg>
}

function Trend({value,goodWhenDown=false}:{value:number|null;goodWhenDown?:boolean}){const good=value!==null&&(goodWhenDown?value<=0:value>=0);return <span className={`text-[11px] font-semibold ${value===null?"text-muted":good?"text-emerald":"text-amber"}`}>{value===null?"sem base anterior":`${value>=0?"↑":"↓"} ${Math.abs(value)}% vs. período anterior`}</span>}
function Panel({title,subtitle,children,className=""}:{title:string;subtitle?:string;children:React.ReactNode;className?:string}){return <section className={`overflow-hidden rounded-xl border border-edge-subtle bg-raised/75 ${className}`}><header className="border-b border-edge-subtle px-4 py-3"><h2 className="text-sm font-bold text-bright">{title}</h2>{subtitle&&<p className="mt-0.5 text-[11px] text-muted">{subtitle}</p>}</header>{children}</section>}

export default function TrafegoPago(){
  const today=saoPauloDay();
  const [from,setFrom]=useState(()=>shiftDay(today,-29)),[to,setTo]=useState(today);
  const [campaign,setCampaign]=useState("Todas"),[adset,setAdset]=useState("Todos"),[creative,setCreative]=useState("Todos");
  const [rows,setRows]=useState<AdRow[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState("");
  useEffect(()=>{let active=true;async function load(){setBusy(true);setError("");try{const days=Math.round((Date.parse(to)-Date.parse(from))/86400000)+1;const previous=shiftDay(from,-days);const r=await fetch(`/api/meta/creatives?since=${previous}&until=${to}`);const body=await r.json();if(!r.ok)throw new Error(body.error||"Falha ao consultar anúncios");if(active)setRows(body.data||[])}catch(e){if(active)setError(e instanceof Error?e.message:"Não foi possível carregar os anúncios") }finally{if(active)setBusy(false)}}void load();return()=>{active=false}},[from,to]);
  const campaigns=[...new Set(rows.map(r=>r.campaign_name))].sort();
  const adsets=[...new Set(rows.filter(r=>campaign==="Todas"||r.campaign_name===campaign).map(r=>r.adset_name))].sort();
  const creatives=[...new Set(rows.filter(r=>(campaign==="Todas"||r.campaign_name===campaign)&&(adset==="Todos"||r.adset_name===adset)).map(r=>r.ad_name))].sort();
  const data=useMemo(()=>{const days=Math.round((Date.parse(to)-Date.parse(from))/86400000)+1,prevFrom=shiftDay(from,-days),prevTo=shiftDay(from,-1);const filtered=rows.filter(r=>(campaign==="Todas"||r.campaign_name===campaign)&&(adset==="Todos"||r.adset_name===adset)&&(creative==="Todos"||r.ad_name===creative));const current=filtered.filter(r=>r.dia>=from&&r.dia<=to),previous=filtered.filter(r=>r.dia>=prevFrom&&r.dia<=prevTo);const total=emptyMetric(),prior=emptyMetric();current.forEach(r=>add(total,r));previous.forEach(r=>add(prior,r));
    const daily=new Map<string,Metric>();current.forEach(r=>{const m=daily.get(r.dia)||emptyMetric();add(m,r);daily.set(r.dia,m)});
    const group=(key:"campaign"|"creative")=>{const map=new Map<string,Group>();for(const [list,isPrev] of [[current,false],[previous,true]] as const)for(const r of list){const id=key==="campaign"?r.campaign_name:r.ad_id;const name=key==="campaign"?r.campaign_name:r.ad_name;const g=map.get(id)||{...emptyMetric(),id,name,campaign:r.campaign_name,adset:r.adset_name,previousSpend:0,previousLeads:0};if(isPrev){g.previousSpend+=Number(r.spend)||0;g.previousLeads+=Number(r.leads)||0}else add(g,r);map.set(id,g)}return [...map.values()].sort((a,b)=>b.spend-a.spend)};
    return {total,prior,daily:[...daily].map(([day,m])=>({day:day.slice(8),...m})),campaigns:group("campaign"),ads:group("creative")};
  },[rows,from,to,campaign,adset,creative]);
  const setPreset=(days:number|"month")=>{setFrom(days==="month"?today.slice(0,7)+"-01":shiftDay(today,-(days-1)));setTo(today)};
  const field="h-10 min-h-10 w-full rounded-lg border border-edge-subtle bg-surface px-3 text-xs text-text outline-none transition-colors focus:border-violet/40";
  const best=data.ads.filter(a=>a.leads>0).sort((a,b)=>a.spend/a.leads-b.spend/b.leads)[0],top=data.ads[0];
  const kpis=[
    {label:"Investimento",value:money(data.total.spend),trend:pct(data.total.spend,data.prior.spend),icon:"money" as IconName,tone:"text-emerald",wash:"bg-emerald/10"},
    {label:"Cliques",value:number(data.total.clicks),trend:pct(data.total.clicks,data.prior.clicks),icon:"click" as IconName,tone:"text-cyan",wash:"bg-cyan/10"},
    {label:"Leads da Meta",value:number(data.total.leads),trend:pct(data.total.leads,data.prior.leads),icon:"leads" as IconName,tone:"text-violet-light",wash:"bg-violet/10"},
    {label:"Custo por lead",value:data.total.leads?money(data.total.spend/data.total.leads):"—",trend:data.prior.leads?pct(data.total.spend/data.total.leads,data.prior.spend/data.prior.leads):null,goodWhenDown:true,icon:"target" as IconName,tone:"text-amber",wash:"bg-amber/10"},
  ];
  return <div className="traffic-dashboard min-h-full p-3 sm:p-4 lg:p-5">
    <header className="traffic-header flex flex-wrap items-center justify-between gap-3 border-b border-edge-subtle pb-3">
      <div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-violet/15 text-violet-light"><Icon name="chart"/></span><div><h1 className="text-2xl font-bold tracking-tight text-bright">Tráfego pago</h1><p className="text-xs text-muted">Performance das campanhas e criativos</p></div></div>
      <div className="flex flex-wrap items-center gap-2"><span className="inline-flex h-10 items-center gap-2 rounded-lg border border-edge-subtle bg-raised px-3 text-xs text-sub"><Icon name="meta" className="h-5 w-5 text-cyan"/><b>Meta Ads</b><span className="text-muted">ativa</span></span><span className="inline-flex h-10 items-center gap-2 rounded-lg border border-edge-subtle bg-raised px-3 text-xs text-muted"><span className="h-2 w-2 rounded-full bg-emerald"/>1 plataforma conectada</span></div>
      <div className="traffic-header-controls">

    <div className="traffic-period-bar"><div className="traffic-period"><div className="flex h-10 items-center rounded-lg border border-edge-subtle bg-surface p-1">{[{l:"7d",v:7},{l:"15d",v:15},{l:"30d",v:30},{l:"Mês",v:"month" as const}].map(p=><button key={p.l} onClick={()=>setPreset(p.v)} className={`h-8 min-h-8 rounded-md px-3 text-xs font-semibold ${from===(p.v==="month"?today.slice(0,7)+"-01":shiftDay(today,-(p.v-1)))&&to===today?"bg-violet text-white":"text-muted hover:text-bright"}`}>{p.l}</button>)}</div><div className="traffic-dates"><label className="min-w-36 flex-1 text-[11px] text-muted">De<input aria-label="Data inicial" type="date" value={from} min={shiftDay(to,-92)} max={to} onInput={e=>{const v=e.currentTarget.value;if(v&&v<=to)setFrom(v)}} className={field}/></label><label className="min-w-36 flex-1 text-[11px] text-muted">Até<input aria-label="Data final" type="date" value={to} min={from} max={shiftDay(from,92)<today?shiftDay(from,92):today} onInput={e=>{const v=e.currentTarget.value;if(v&&v>=from&&v<=today)setTo(v)}} className={field}/></label></div></div></div>
      </div>
    </header>
    <section aria-label="Filtros de tráfego" className="mt-3 rounded-xl border border-edge-subtle bg-raised/75 p-3">
      <div className="flex flex-wrap items-end gap-2"><span className="mb-2 hidden text-muted lg:block"><Icon name="filter"/></span><label className="min-w-40 flex-1 text-[11px] text-muted">Campanha<select aria-label="Campanha" value={campaign} onChange={e=>{setCampaign(e.target.value);setAdset("Todos");setCreative("Todos")}} className={field}><option>Todas</option>{campaigns.map(v=><option key={v}>{v}</option>)}</select></label><label className="min-w-40 flex-1 text-[11px] text-muted">Conjunto<select aria-label="Conjunto de anúncios" value={adset} onChange={e=>{setAdset(e.target.value);setCreative("Todos")}} className={field}><option>Todos</option>{adsets.map(v=><option key={v}>{v}</option>)}</select></label><label className="min-w-40 flex-1 text-[11px] text-muted">Criativo<select aria-label="Criativo" value={creative} onChange={e=>setCreative(e.target.value)} className={field}><option>Todos</option>{creatives.map(v=><option key={v}>{v}</option>)}</select></label></div>
    </section>

    {error&&<p role="alert" className="mt-3 rounded-lg border border-rose/20 bg-rose/10 px-4 py-3 text-sm text-rose">{error}</p>}
    <section className="mt-3 grid grid-cols-2 gap-2 xl:grid-cols-4">{kpis.map(k=><article key={k.label} className="flex min-h-24 items-center gap-2 rounded-xl border border-edge-subtle bg-raised/75 p-2.5 sm:gap-3 sm:p-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg sm:h-11 sm:w-11 sm:rounded-xl ${k.wash} ${k.tone}`}><Icon name={k.icon} className="h-4 w-4 sm:h-5 sm:w-5"/></span><div className="min-w-0"><p className="text-[10px] font-medium text-muted sm:text-[11px]">{k.label}</p><strong className="block whitespace-nowrap text-base font-bold tabular-nums text-bright sm:text-xl">{busy?"—":k.value}</strong>{!busy&&<Trend value={k.trend} goodWhenDown={"goodWhenDown" in k&&!!k.goodWhenDown}/>}</div></article>)}</section>

    <section className="mt-3 grid gap-3 xl:grid-cols-[1.55fr_.8fr]">
      <Panel title="Evolução de investimento e leads" subtitle="Ritmo diário no período selecionado"><div className="h-64 px-2 pb-2 pt-4">{busy?<div className="m-4 h-48 animate-pulse rounded-lg bg-surface"/>:<ResponsiveContainer width="100%" height="100%"><ComposedChart data={data.daily}><CartesianGrid stroke="var(--color-edge-subtle)" vertical={false}/><XAxis dataKey="day" tick={{fill:"var(--color-muted)",fontSize:11}} tickLine={false} axisLine={false}/><YAxis yAxisId="left" tickFormatter={v=>compactMoney(v)} tick={{fill:"var(--color-muted)",fontSize:10}} tickLine={false} axisLine={false} width={68}/><YAxis yAxisId="right" orientation="right" tick={{fill:"var(--color-muted)",fontSize:10}} tickLine={false} axisLine={false} width={28}/><Tooltip contentStyle={{background:"var(--color-surface)",border:"1px solid var(--color-edge)",borderRadius:8,fontSize:12}} formatter={(v,name)=>name==="Investimento"?money(Number(v)):number(Number(v))}/><Bar yAxisId="left" dataKey="spend" name="Investimento" fill="var(--color-violet)" radius={[3,3,0,0]} maxBarSize={18}/><Line yAxisId="right" type="monotone" dataKey="leads" name="Leads" stroke="var(--color-cyan)" strokeWidth={2} dot={{r:2,fill:"var(--color-cyan)"}}/></ComposedChart></ResponsiveContainer>}</div></Panel>
      <Panel title="Distribuição do investimento" subtitle="Participação por campanha"><div className="grid min-h-64 grid-cols-1 items-center gap-2 p-3">{busy?<div className="col-span-2 m-4 h-44 animate-pulse rounded-lg bg-surface"/>:<><div className="h-40"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.campaigns.filter(c=>c.spend>0)} dataKey="spend" nameKey="name" innerRadius={45} outerRadius={67} paddingAngle={2}>{data.campaigns.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip contentStyle={{background:"var(--color-surface)",border:"1px solid var(--color-edge)",borderRadius:8,fontSize:11}} formatter={v=>money(Number(v))}/></PieChart></ResponsiveContainer></div><div className="space-y-3">{data.campaigns.slice(0,5).map((c,i)=><div key={c.id} className="flex items-center justify-between gap-3 text-xs"><span className="min-w-0 truncate text-sub"><i className="mr-2 inline-block h-2 w-2 rounded-full" style={{background:colors[i%colors.length]}}/>{c.name}</span><b className="shrink-0 tabular-nums text-bright">{data.total.spend?(c.spend/data.total.spend*100).toFixed(0):0}%</b></div>)}</div></>}</div></Panel>
    </section>

    <section className="mt-3 grid gap-3 2xl:grid-cols-[.95fr_1.45fr_.8fr]">
      <Panel title="Campanhas com melhor desempenho" subtitle="Ordenadas por investimento"><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-xs"><thead className="bg-surface/40 text-[10px] uppercase tracking-wide text-muted"><tr><th className="px-4 py-2">Campanha</th><th className="px-3 py-2 text-right">Investimento</th><th className="px-3 py-2 text-right">Leads</th><th className="px-4 py-2 text-right">CPL</th></tr></thead><tbody className="divide-y divide-edge-subtle">{data.campaigns.slice(0,8).map(c=><tr key={c.id} className="hover:bg-surface/30"><td className="max-w-48 truncate px-4 py-2.5 font-medium text-sub" title={c.name}>{c.name}</td><td className="px-3 py-2.5 text-right tabular-nums text-bright">{money(c.spend)}</td><td className="px-3 py-2.5 text-right tabular-nums text-emerald">{number(c.leads)}</td><td className="px-4 py-2.5 text-right tabular-nums text-cyan">{c.leads?money(c.spend/c.leads):"—"}</td></tr>)}</tbody></table></div></Panel>
      <Panel title="Criativos que mais performaram" subtitle="Investimento e resultados por criativo"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="bg-surface/40 text-[10px] uppercase tracking-wide text-muted"><tr><th className="px-4 py-2">Criativo</th><th className="px-3 py-2">Campanha</th><th className="px-3 py-2 text-right">Gasto</th><th className="px-3 py-2 text-right">Leads Meta</th><th className="px-4 py-2 text-right">CPL</th></tr></thead><tbody className="divide-y divide-edge-subtle">{data.ads.slice(0,10).map((a,i)=><tr key={a.id} className="hover:bg-surface/30"><td className="px-4 py-2.5"><div className="flex items-center gap-2"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-md text-[10px] font-bold ${i<3?"bg-violet/15 text-violet-light":"bg-panel text-muted"}`}>{i+1}</span><span className="min-w-0"><b className="block max-w-44 truncate font-semibold text-bright" title={a.name}>{a.name}</b><small className="text-[9px] text-muted">ID …{a.id.slice(-6)}</small></span></div></td><td className="max-w-44 truncate px-3 py-2.5 text-muted" title={a.campaign}>{a.campaign}</td><td className="px-3 py-2.5 text-right font-semibold tabular-nums text-bright">{money(a.spend)}</td><td className="px-3 py-2.5 text-right tabular-nums text-emerald">{number(a.leads)}</td><td className="px-4 py-2.5 text-right font-semibold tabular-nums text-cyan">{a.leads?money(a.spend/a.leads):"—"}</td></tr>)}</tbody></table></div></Panel>
      <Panel title="Insights e recomendações"><div className="space-y-2 p-3">{top&&<div className="flex gap-3 rounded-lg bg-violet/8 p-3"><span className="text-violet-light"><Icon name="chart"/></span><p className="text-xs leading-relaxed text-sub"><b className="text-bright">Maior investimento:</b> {top.name}, com {money(top.spend)} ({data.total.spend?(top.spend/data.total.spend*100).toFixed(0):0}% do total).</p></div>}{best&&<div className="flex gap-3 rounded-lg bg-emerald/8 p-3"><span className="text-emerald"><Icon name="target"/></span><p className="text-xs leading-relaxed text-sub"><b className="text-bright">Melhor CPL:</b> {best.name}, a {money(best.spend/best.leads)} por lead da Meta.</p></div>}<div className="flex gap-3 rounded-lg bg-amber/8 p-3"><span className="text-amber"><Icon name="bulb"/></span><p className="text-xs leading-relaxed text-sub"><b className="text-bright">Leitura segura:</b> gasto e leads vêm da Meta por ID do anúncio. Receita e ROAS ainda não têm integração.</p></div></div></Panel>
    </section>
    <details className="mt-3 rounded-lg border border-edge-subtle bg-raised/50 px-4 py-3 text-xs text-muted"><summary className="cursor-pointer font-semibold text-sub">Sobre os dados e limitações</summary><p className="mt-2 leading-relaxed">Investimento, cliques e leads vêm da tabela diária da Meta Ads e são agrupados pelo ID do anúncio. O custo por lead usa apenas os leads atribuídos pela própria Meta. Captações das landing pages não possuem esse ID e, por isso, não foram misturadas por nome. Google Ads, TikTok Ads, receita, compras e ROAS serão exibidos quando essas fontes estiverem conectadas com identificadores confiáveis.</p></details>
  </div>
}
