-- Create the table for AI Qualified Leads
CREATE TABLE IF NOT EXISTS leads_qualificados_ia (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    nome_cliente text,
    usuario text,
    bio text,
    email text,
    telefone text,
    stage text default 'Qualificação de Leads por IA'
);

-- Enable Row Level Security (optional but recommended)
-- alter table leads_qualificados_ia enable row level security;
-- create policy "Enable read access for all users" on leads_qualificados_ia for select using (true);
-- create policy "Enable insert for all users" on leads_qualificados_ia for insert with check (true);
-- create policy "Enable update for all users" on leads_qualificados_ia for update using (true);
